language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g yarn
  - yarn global add purescript@^0.13.6 pulp@^14.0.0 bower purescript-psa@^0.7.3
  - export PATH="$PATH:`yarn global bin`"
  - bower install
script:
  - pulp test --include examples
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
